apiVersion: v1
kind: Service
metadata:
  name: ride-matching
spec:
  selector:
    app: ride-matching
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  type: ClusterIP
